package com.kyriewang.kkbbs.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.parent_id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Long parent_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.type
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_creator
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Long comment_creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmt_create
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Long gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.gmt_modified
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Long gmt_modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.like_count
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Long like_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_count
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Integer comment_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.receiver_id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private Long receiver_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.receiver_name
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    private String receiver_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.parent_id
     *
     * @return the value of comment.parent_id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Long getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.parent_id
     *
     * @param parent_id the value for comment.parent_id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setParent_id(Long parent_id) {
        this.parent_id = parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.type
     *
     * @return the value of comment.type
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.type
     *
     * @param type the value for comment.type
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_creator
     *
     * @return the value of comment.comment_creator
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Long getComment_creator() {
        return comment_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_creator
     *
     * @param comment_creator the value for comment.comment_creator
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setComment_creator(Long comment_creator) {
        this.comment_creator = comment_creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmt_create
     *
     * @return the value of comment.gmt_create
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmt_create
     *
     * @param gmt_create the value for comment.gmt_create
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.gmt_modified
     *
     * @return the value of comment.gmt_modified
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.gmt_modified
     *
     * @param gmt_modified the value for comment.gmt_modified
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.like_count
     *
     * @return the value of comment.like_count
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Long getLike_count() {
        return like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.like_count
     *
     * @param like_count the value for comment.like_count
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setLike_count(Long like_count) {
        this.like_count = like_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_count
     *
     * @return the value of comment.comment_count
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Integer getComment_count() {
        return comment_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_count
     *
     * @param comment_count the value for comment.comment_count
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setComment_count(Integer comment_count) {
        this.comment_count = comment_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.receiver_id
     *
     * @return the value of comment.receiver_id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public Long getReceiver_id() {
        return receiver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.receiver_id
     *
     * @param receiver_id the value for comment.receiver_id
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setReceiver_id(Long receiver_id) {
        this.receiver_id = receiver_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.receiver_name
     *
     * @return the value of comment.receiver_name
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public String getReceiver_name() {
        return receiver_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.receiver_name
     *
     * @param receiver_name the value for comment.receiver_name
     *
     * @mbg.generated Wed Apr 28 23:53:18 CST 2021
     */
    public void setReceiver_name(String receiver_name) {
        this.receiver_name = receiver_name == null ? null : receiver_name.trim();
    }
}