package com.kyriewang.kkbbs.model;

public class Notification {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.id
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.notifier
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.receiver
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.outerid
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.type
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.gmt_create
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private Long gmt_create;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.status
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.out_title
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private String out_title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notification.out_username
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    private String out_username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.id
     *
     * @return the value of notification.id
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.id
     *
     * @param id the value for notification.id
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.notifier
     *
     * @return the value of notification.notifier
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.notifier
     *
     * @param notifier the value for notification.notifier
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.receiver
     *
     * @return the value of notification.receiver
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.receiver
     *
     * @param receiver the value for notification.receiver
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.outerid
     *
     * @return the value of notification.outerid
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.outerid
     *
     * @param outerid the value for notification.outerid
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.type
     *
     * @return the value of notification.type
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.type
     *
     * @param type the value for notification.type
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.gmt_create
     *
     * @return the value of notification.gmt_create
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.gmt_create
     *
     * @param gmt_create the value for notification.gmt_create
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.status
     *
     * @return the value of notification.status
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.status
     *
     * @param status the value for notification.status
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.out_title
     *
     * @return the value of notification.out_title
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public String getOut_title() {
        return out_title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.out_title
     *
     * @param out_title the value for notification.out_title
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setOut_title(String out_title) {
        this.out_title = out_title == null ? null : out_title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notification.out_username
     *
     * @return the value of notification.out_username
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public String getOut_username() {
        return out_username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notification.out_username
     *
     * @param out_username the value for notification.out_username
     *
     * @mbg.generated Mon Nov 23 21:59:58 CST 2020
     */
    public void setOut_username(String out_username) {
        this.out_username = out_username == null ? null : out_username.trim();
    }
}